### ISSUE TITLE
Friend list records appearance

### ISSUE THREAD

**Issue by pswierzbinski** [MyPHPoL/MyCommsFront#122]
In the main page of friends, the "Your friends" list shows the user banners smaller as if waiting for hover to show management buttons was bugged. 

![image](https://github.com/user-attachments/assets/bea56faa-10cd-4c51-a2d8-98f681a1fb2c)

@Syadaisu please fix it

**Comment by Syadaisu** [comment]
Nah Neighbor

**Comment by pswierzbinski** [comment]
Fine, I'll do it myself later

**Comment by CarboSauce** [comment]
We no longer intend to support this software as the maintenance burden too much. You are free to fork it to support it for longer

**Comment by CarboSauce** [comment]
After further consideration, we'd be very happy to accept the PR that addresses that issue.

**Comment by pswierzbinski** [comment]
Fixed 🫡
[The fix in question](https://github.com/MyPHPoL/MyCommsFront/commit/f4cdae69b77cb1c48c2217231522713cfb70f0a3)
